
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.11.5"

[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "2.0.0"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/d4l3k/messagediff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.2.1"

[[constraint]]
  name = "github.com/gosuri/uiprogress"

[[constraint]]
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/mattn/go-zglob"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/ralekseenkov/govaluate"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.6.1"

[[constraint]]
  name = "k8s.io/kubernetes"
