# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

spark:
  image:
    repository: mirantisworkloads/
    name: spark
    tag: 2.2.0-r1
    pullPolicy: IfNotPresent
  master:
    replicas: 1  # 1 or 2
    daemonMemory: "1g"
    rpcPort: 7077
    rpcNodePort: null
    webuiPort: 8080
    webuiNodePort: null
    restPort: 6066
    restNodePort: null
    resources:
      #requests:
      #  cpu: "100m"
      #  memory: "512Mi"
  worker:
    replicas: 3
    daemonMemory: "1g"
    executorMemory: "1g"
    resources:
      #requests:
      #  cpu: "100m"
      #  memory: "512Mi"

configs:
  sparkDefaults:
  sparkEnv:

ingress:
  enabled: false
  hosts: []
  tls:
    enabled: false
    secretName: ""
  annotations: {}

service:
  type: NodePort # or ClusterIP or LoadBalancer
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}

prometheusExporter:
  enabled: false

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: IfNotPresent
  # external logstash hosts
  logstashHost:
    - "" # host:port

zookeeper:
  # if disabled, subchart will not be deployed
  deployChart: false
  # these addresses will be used if subchart deployment is disabled
  addresses:
    zookeeper: ""
  # this path will be used as prefix for spark deployment, useful for multiple sparks per single zookeeper
  path: "/spark"

cassandra:
  enabled: false
  deployChart: false
  externalAddress: ""
