apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      {{ if .Values.istio.enabled }}
      annotations:
        alpha.istio.io/sidecar: injected
        alpha.istio.io/version: jenkins@ubuntu-16-04-build-12ac793f80be71-0.1.6-dab2033
      {{ end }}
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{ if .Values.istio.enabled }}
      initContainers:
      - name: init
        image: docker.io/istio/init:0.1
        imagePullPolicy: Always
        args:
        - -p
        - '15001'
        - -u
        - '1337'
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      - name: enable-core-dump
        image: alpine
        imagePullPolicy: Always
        command:
        - /bin/sh
        args:
        - -c
        - sysctl -w kernel.core_pattern=/tmp/core.%e.%p.%t && ulimit -c unlimited
        securityContext:
          privileged: true
      {{ end }}
      containers:
      {{ if .Values.istio.enabled }}
      - args:
        - proxy
        - sidecar
        - -v
        - "2"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/istio/proxy_debug:0.1
        imagePullPolicy: Always
        name: proxy
        resources: {}
        securityContext:
          runAsUser: 1337
      {{ end }}
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TWEEVIZ_STORAGE
          value: {{ .Values.storage }}
        {{- if eq .Values.storage "cassandra" }}
        - name: TWEEVIZ_CASSANDRA_ADDRESS
          {{- if .Values.cassandra.deployChart }}
          value: {{- printf "cassandra-%s" .Release.Name | trunc 55 | trimSuffix "-" }}
          {{- else }}
          value: "{{ (split ":" .Values.cassandra.addresses.cassandra)._0 }}"
          {{- end }}
        - name: TWEEVIZ_CASSANDRA_KEYSPACE
          value: "{{ .Values.cassandra.keyspace }}"
        - name: TWEEVIZ_CASSANDRA_TABLE
          value: "{{ .Values.cassandra.table }}"
        {{- end  }}
        {{- if eq .Values.storage "hdfs" }}
        - name: TWEEVIZ_HDFS_ADDRESS
          {{- if .Values.hdfs.deployChart }}
          value: {{ printf "hdfs-namenode-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
          {{- else }}
          value: "{{ (split ":" .Values.hdfs.addresses.namenode)._0 }}"
          {{- end }}
        - name: TWEEVIZ_HDFS_PORT
          {{- if .Values.hdfs.deployChart }}
          value: "{{ .Values.hdfs.namenode.port }}"
          {{- else }}
          value: "{{ (split ":" .Values.hdfs.addresses.namenode)._1 }}"
          {{- end }}
        - name: TWEEVIZ_HDFS_PATH
          value: "{{ .Values.hdfs.path }}"
        {{- end }}
        - name: TWEEVIZ_MIN_POPULARITY
          value: "{{ .Values.minPopularity }}"
        - name: TWEEVIZ_TOP_LIST_SIZE
          value: "{{ .Values.topListSize }}"
        - name: TWEEVIZ_HEADER
          value: "{{ .Values.header }}"
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-ce", "wget -O - -T {{ .Values.probePeriodSeconds }} -q localhost:{{ .Values.port }}/stats | grep weight" ]
          initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}
          periodSeconds: {{ .Values.probePeriodSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
