# Default values for kafka.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3
antiAffinity: "soft" # or "hard"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
port: 9092

# You can pass custom config files here. Default configs will be used otherwise.
# Note, that the following configs will be overriden:
# - broker.id
# - zookeeper.connect
# - advertised.listeners
# - listeners
# - log.dirs
configFiles:
  #server.properties: |
  #  zookeeper.connection.timeout.ms=10000

image:
  repository: mirantisworkloads/
  name: kafka
  tag: 0.11.0.0-r1
  pullPolicy: IfNotPresent

persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass: ""
  volumeSize: 10Gi

  hostPath: ""

prometheusExporter:
  enabled: false

heapSize: 1G
resources:
  #requests:
  #  cpu: 1
  #  memory: 1Gi
  #limits:
    #cpu: 4
    #memory: 4Gi

zookeeper:
  # if disabled, subchart will not be deployed
  deployChart: false
  # these addresses will be used if subchart deployment is disabled
  addresses:
    zookeeper: ""
# if serviceCatalog is enabled, zookeper-secret data will be used as ZK_CONNECT env variable
  serviceCatalog:
    enabled: false
    secretName: ""

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: IfNotPresent
  # external logstash hosts
  logstashHost:
    - "" # host:port
