apiVersion: v1
kind: Service
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    app: {{ template "cassandra.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: jmx
    port: 7199
    targetPort: 7199
  - name: cql
    port: {{ default 9042 .Values.config.ports.cql }}
    targetPort: {{ default 9042 .Values.config.ports.cql }}
  - name: thrift
    port: {{ default 9160 .Values.config.ports.thrift }}
    targetPort: {{ default 9160 .Values.config.ports.thrift }}
  selector:
    app: {{ template "cassandra.fullname" . }}
